server:
  port: 8001
spring:
  application:
    name: server-edu
#  profiles:
#    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 159629zxc
    hikari:
     connection-test-query: SELECT 1
     connection-timeout: 60000
     idle-timeout: 500000
     max-lifetime: 540000
     maximum-pool-size: 12
     minimum-idle: 10
     pool-name: GuliHikariPool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


#mybatis:
#  mapper-locations: classpath:/*.xml
#  type-aliases-package: com.phoenixhell.springcloud.entities
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
#      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 设置日志级别
#logging:
#  level:
#    root: info
