server:
  port: 8003
  tomcat:
    accesslog:
      file-date-format:
spring:
  application:
    name: server-vod
  servlet:
    multipart:
      #设置总上传单个文件大小 默认1M
      max-file-size: 1024MB
      #设置总上传数据文件大小默认10M
      max-request-size: 1024MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
aliyun:
  vod:
    #accessKeyId: LTAI4GBn6ndauEMrJEngWjWK
    accessKeyId: LTAI4G3eAAf3bJ3ezjr3cPv3
    #accessKeySecret: EbmellO9i65ynQlggkV9xxvbaKV1rq
    accessKeySecret: AMswshKGYv3jUeIIY9ds6SsD943NcC
