server:
  port: 8009
spring:
  application:
    name: server-acl
  profiles:
    active: home
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 159629zxc
    hikari:
     connection-test-query: SELECT 1
     connection-timeout: 60000
     idle-timeout: 500000
     max-lifetime: 540000
     maximum-pool-size: 12
     minimum-idle: 10
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
management:
  endpoints:
    web:
      exposure:
        include: "*"
#mybatis:
#  mapper-locations: classpath:/*.xml
#  type-aliases-package: com.phoenixhell.springcloud.entities
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#3.1.1开始不再需要这一步  @TableLogic 即可解決
#mybatis-plus.global-config.sql-injector=com.baomidou.mybatisplus.mapper.LogicSqlInjector
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 设置日志级别
#logging:
#  level:
#    root: info
#logging:
#  level:
    #feign日志监控的接口 和级别
#    com.phoenixhell.springcloud.service.PaymentFeignService: debug
#feign:
#  hystrix:
#    enabled: true
# 设置hystrix超时时间，默认1000ms
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000