server:
  port: 8003
spring:
  application:
    name: service-vod
aliyun:
  vod:
    #accessKeyId: LTAI4GBn6ndauEMrJEngWjWK
    accessKeyId: LTAI4G3eAAf3bJ3ezjr3cPv3
    #accessKeySecret: EbmellO9i65ynQlggkV9xxvbaKV1rq
    accessKeySecret: AMswshKGYv3jUeIIY9ds6SsD943NcC