spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.1.100:3306/guli?serverTimezone=GMT%2B8
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123456